#ifndef _INC_ERROR_CODES_H_
#define _INC_ERROR_CODES_H_

typedef enum
{   
    OK = 0,

    SETTINGS_ARGUMENT_ERROR = 10,
    SETTINGS_VALUE_ERROR,
    SETTINGS_ARGUMENT_OR_VALUE_ERROR,
    SETTINGS_UNKNOWN_ERROR,
    SETTINGS_ARGUMENT_ADDR_ERROR,
    SETTINGS_VALUE_ADDR_ERROR,

    CONFIG_FILE_OPEN_ERROR = 20,
    CONFIG_FILE_ROWS_COUNT_READ_ERROR,
    CONFIG_FILE_COLS_COUNT_READ_ERROR,
    CONFIG_FILE_COL_READ_ERROR,
    CONFIG_FILE_POINTS_COUNT_IS_MANY,

    ARRAY_POINTER_ERROR = 30,
    SUB_ARRAY_POINTER_ERROR,
    ARRAY_SIZE_ERROR_AFTER_CREAT,
    ARRAY_IS_NOT_FOUND,
    ARRAY_ROWS_COUNT_OVERRANGE,
    ARRAY_COLS_COUNT_OVERRANGE,
    ARRAY_ROWS_COUNT_UNDERRANGE,
    ARRAY_COLS_COUNT_UNDERRANGE,
    ARRAY_ROW_NUM_OVERRANGE,
    ARRAY_COL_NUM_OVERRANGE,
    ARRAY_ROW_NUM_UNDERRANGE,
    ARRAY_COL_NUM_UNDERRANGE,
    ARRAY_UNKNOWN_ERROR,

    POINTS_OTHER_ERROR = 50,

    STATISTICS_STEP_NUM_OVERRANGE = 60,

    DISPLAY_CLEAR_ERROR = 70

}error_codes_t;

void error_print(const char * error_text, error_codes_t error_code);

#endif