#ifndef _STATUS_CODES_H_
#define _STATUS_CODES_H_

typedef enum
{   
    OK = 0,

    SETTINGS_ARGUMENT_ERROR = 10,
    SETTINGS_VALUE_ERROR,
    SETTINGS_ARGUMENT_OR_VALUE_ERROR,

    CONFIG_FILE_OPEN_ERROR = 20,
    CONFIG_FILE_ROWS_COUNT_READ_ERROR,
    CONFIG_FILE_COLS_COUNT_READ_ERROR,
    CONFIG_FILE_COL_READ_ERROR,
    CONFIG_FILE_POINTS_COUNT_IS_MANY,

    ARRAY_POINTER_ERROR = 30,
    SUB_ARRAY_POINTER_ERROR,
    ARRAY_SIZE_ERROR_AFTER_CREAT,
    ARRAY_IS_NOT_FOUND,
    ARRAY_ROWS_COUNT_OVERRANGE,
    ARRAY_COLS_COUNT_OVERRANGE,
    ARRAY_ROWS_COUNT_UNDERRANGE,
    ARRAY_COLS_COUNT_UNDERRANGE,
    ARRAY_ROW_NUM_OVERRANGE,
    ARRAY_COL_NUM_OVERRANGE

}status_t;

#endif